In [35]:
#import required packages
import numpy as np 
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')

In [37]:
#import the dataset
df = pd.read_csv("diabetes.csv")

In [38]:
#display 5 data values from the dataset
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [39]:
#Selecting the required feartures
df1 = df[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin']]

In [41]:
#displaying the values after feature extration
df1.head(3)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin
0            6      148             72             35        0
1            1       85             66             29        0
2            8      183             64              0        0

In [42]:
#selecting only 5 data values
df1 = df1[0:5]

In [43]:
#displaying  the content
df1

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin
0            6      148             72             35        0
1            1       85             66             29        0
2            8      183             64              0        0
3            1       89             66             23       94
4            0      137             40             35      168

In [44]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
#v = foo[:,1]
v = min_max_scaler.fit_transform(df1)
#foo[:,1] = v_scaled
print(v)

[[0.75       0.64285714 1.         1.         0.        ]
 [0.125      0.         0.8125     0.82857143 0.        ]
 [1.         1.         0.75       0.         0.        ]
 [0.125      0.04081633 0.8125     0.65714286 0.55952381]
 [0.         0.53061224 0.         1.         1.        ]]


In [45]:
#find covariance matrix
c = np.cov(v)

In [47]:
#display covariance matrix
print(c)

[[ 0.16836735  0.13410395  0.06919643  0.02504479 -0.09402332]
 [ 0.13410395  0.18462755 -0.05924107  0.11124292 -0.01631924]
 [ 0.06919643 -0.05924107  0.2625     -0.10801233 -0.21530612]
 [ 0.02504479  0.11124292 -0.10801233  0.1146902   0.03184854]
 [-0.09402332 -0.01631924 -0.21530612  0.03184854  0.25018742]]


In [48]:
#find the eigen values and eigen vectors
eig_val,eig_vec = np.linalg.eig(c)

In [49]:
print("Eigen Vectors\n", eig_vec)

Eigen Vectors
 [[-0.2589643  -0.54291811 -0.56819956  0.53181659 -0.18027143]
 [ 0.06045357 -0.70390724 -0.0433157  -0.69742939  0.11214261]
 [-0.68605992  0.14776351 -0.13189528 -0.08875418  0.69441635]
 [ 0.22798518 -0.40651087  0.57348088  0.47176729  0.48096463]
 [ 0.63767343  0.15056355 -0.57358201  0.01793547  0.49130968]]


In [50]:
print("Eigen Values\n", eig_val)

Eigen Values
 [5.29854117e-01 3.68230828e-01 7.44614142e-02 5.78177295e-18
 7.82615681e-03]


In [51]:
#higest 2 values of eigen values corresponding eigen vectors
b = np.array([[0.03979592 , 0.05464817],
 [ 0.05464817 , 0.14699433 ],
 [-0.009375  , -0.13126488 ],
 [ 0.04226297 , 0.12702625 ],
 [-0.02346939 , 0.0483552 ]])

In [52]:
#multiplying
a = c.dot(b)

In [53]:
#reduced matrix
print("REDUCED MATRIX TO 5X2 USING PCA")
print(a)

REDUCED MATRIX TO 5X2 USING PCA
[[ 0.01664529  0.01846526]
 [ 0.02106619  0.05558566]
 [-0.00245644 -0.06351525]
 [ 0.0121882   0.04800766]
 [-0.0071408   0.03686856]]
