In [2]:
#import required packages
import numpy as np 
import pandas as pd

In [14]:
#import the dataset
df = pd.read_csv(r"C:\Users\Admin\Desktop\diabetes.csv")

In [15]:
#display 5 data values from the dataset
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35       96  33.6   
1            1       85             66             29       88  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [16]:
#Selecting the required feartures
df1 = df[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin']]

In [17]:
#displaying the values after feature extration
df1.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin
0            6      148             72             35       96
1            1       85             66             29       88
2            8      183             64              0        0
3            1       89             66             23       94
4            0      137             40             35      168
5            5      116             74              0        0
6            3       78             50             32       88
7           10      115              0              0        0
8            2      197             70             45      543
9            8      125             96              0        0

In [18]:
#selecting only 5 data values
df1 = df1[0:5]

In [19]:
#displaying  the content
df1

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin
0            6      148             72             35       96
1            1       85             66             29       88
2            8      183             64              0        0
3            1       89             66             23       94
4            0      137             40             35      168

In [21]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
#v = foo[:,1]
v = min_max_scaler.fit_transform(df1)
#foo[:,1] = v_scaled
print(v)

[[0.75       0.64285714 1.         1.         0.57142857]
 [0.125      0.         0.8125     0.82857143 0.52380952]
 [1.         1.         0.75       0.         0.        ]
 [0.125      0.04081633 0.8125     0.65714286 0.55952381]
 [0.         0.53061224 0.         1.         1.        ]]


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [22]:
c = np.cov(v)

In [23]:
c

array([[ 0.03979592,  0.05464817, -0.009375  ,  0.04226297, -0.02346939],
       [ 0.05464817,  0.14699433, -0.13126488,  0.12702625,  0.0483552 ],
       [-0.009375  , -0.13126488,  0.2625    , -0.10801233, -0.21530612],
       [ 0.04226297,  0.12702625, -0.10801233,  0.1146902 ,  0.03184854],
       [-0.02346939,  0.0483552 , -0.21530612,  0.03184854,  0.25018742]])

In [24]:
eig_val,eig_vec = np.linalg.eig(c)

In [25]:
print("Eigen Vectors\n", eig_vec)

Eigen Vectors
 [[ 0.0522741  -0.34191231  0.77103916  0.39763794 -0.35741583]
 [ 0.37879378 -0.54045893  0.1505762  -0.73126008  0.08369539]
 [-0.67330933 -0.09009232  0.36430394 -0.1359427   0.62236657]
 [ 0.31343209 -0.49811987 -0.26825337  0.53723076  0.54135032]
 [ 0.54972499  0.57858455  0.42207605 -0.006742    0.42994035]]


In [26]:
print("Eigen Values\n", eig_val)

Eigen Values
 [5.63143505e-01 2.24994064e-01 1.84874211e-02 3.83631281e-17
 7.54287666e-03]


In [27]:
#covariance matrix
print(c)

[[ 0.03979592  0.05464817 -0.009375    0.04226297 -0.02346939]
 [ 0.05464817  0.14699433 -0.13126488  0.12702625  0.0483552 ]
 [-0.009375   -0.13126488  0.2625     -0.10801233 -0.21530612]
 [ 0.04226297  0.12702625 -0.10801233  0.1146902   0.03184854]
 [-0.02346939  0.0483552  -0.21530612  0.03184854  0.25018742]]


In [29]:
#higest 2 values of eigen values corresponding eigen vectors
b = np.array([[0.03979592 , 0.05464817],
 [ 0.05464817 , 0.14699433 ],
 [-0.009375  , -0.13126488 ],
 [ 0.04226297 , 0.12702625 ],
 [-0.02346939 , 0.0483552 ]])

In [30]:
#multiplying
a = c.dot(b)

In [32]:
#Rotation matix, reduced matrix
print("REDUCED MATRIX TO 5X2 USING PCA")
print(a)

REDUCED MATRIX TO 5X2
[[ 0.006995    0.01567199]
 [ 0.01567199  0.06029812]
 [-0.00951923 -0.07839612]
 [ 0.01373594  0.05126867]
 [-0.0007987   0.05023098]]
